FROM quay.io/jupyter/scipy-notebook:python-3.13.15
USER root
# 1. Node.js & npm als root installieren, damit hatch_jupyter_builder darauf zugreifen kann
RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends git nodejs npm && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER $NB_UID

# 2. Jupytext (Backend-Abhängigkeit) installieren
RUN pip install --no-cache-dir jupytext

# 3. Repository klonen, im 'extension/'-Ordner bauen & installieren
RUN git clone https://github.com/msteffens-hnbk-de/jupyterlitext.git /tmp/jupyterlitext && \
    cd /tmp/jupyterlitext/extension && \
    pip install --no-cache-dir . && \
    rm -rf /tmp/jupyterlitext